(function(){
  const C=window.KORANER_ALO_CONFIG||{}; const U=(C.supabaseUrl||'').replace(/\/$/,''); const K=C.supabaseAnonKey||''; const KEY='ka_supabase_session_v1';
  function save(s){localStorage.setItem(KEY,JSON.stringify(s));window.KORANER_ACCESS_TOKEN=s.access_token;}
  function session(){try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}}
  function msg(t){const e=document.getElementById('ka-auth-msg');if(e)e.textContent=t||''}
  async function req(path,body){const r=await fetch(U+'/auth/v1/'+path,{method:'POST',headers:{apikey:K,'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.msg||j.error_description||j.message||'Authentication failed');return j}
  async function refresh(){const s=session();if(!s?.refresh_token)return false;try{const r=await fetch(U+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{apikey:K,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:s.refresh_token})});if(!r.ok)throw 0;save(await r.json());return true}catch{return false}}
  function hide(){document.getElementById('ka-auth-overlay')?.remove();document.body.classList.remove('overflow-hidden')}
  function show(){if(document.getElementById('ka-auth-overlay'))return;document.body.classList.add('overflow-hidden');const d=document.createElement('div');d.id='ka-auth-overlay';d.className='fixed inset-0 z-[99999] bg-slate-950/95 backdrop-blur-md flex items-center justify-center p-4';d.innerHTML='<div class="glass-panel w-full max-w-md p-7 rounded-3xl border border-amber-500/20"><div class="text-center mb-6"><div class="w-14 h-14 mx-auto rounded-2xl bg-amber-500/10 flex items-center justify-center"><i class="fa-solid fa-lock text-amber-400 text-2xl"></i></div><h2 class="text-2xl font-bold mt-3">কোরআনের আলো</h2><p class="text-slate-400 text-sm">নিরাপদে প্রবেশ করুন</p></div><form id="ka-auth-form" class="space-y-3"><input id="ka-email" type="email" required placeholder="ইমেইল" class="glass-input w-full p-3 rounded-xl"><input id="ka-pass" type="password" minlength="6" required placeholder="পাসওয়ার্ড" class="glass-input w-full p-3 rounded-xl"><button class="w-full py-3 rounded-xl bg-gradient-to-r from-amber-600 to-yellow-500 text-slate-950 font-bold">প্রবেশ / নতুন অ্যাকাউন্ট</button></form><p id="ka-auth-msg" class="text-xs text-center text-amber-300 mt-4 min-h-5"></p><p class="text-[11px] text-slate-500 text-center mt-3">প্রথমবার হলে একই ফর্মে অ্যাকাউন্ট তৈরি হবে। Email confirmation চাইলে ইমেইলের link-এ একবার ক্লিক করুন।</p></div>';document.body.appendChild(d);d.querySelector('form').onsubmit=async e=>{e.preventDefault();msg('প্রবেশের চেষ্টা চলছে…');const email=d.querySelector('#ka-email').value.trim(),password=d.querySelector('#ka-pass').value;try{let j;try{j=await req('token?grant_type=password',{email,password})}catch{j=await req('signup',{email,password})}if(j.access_token){save(j);hide();if(window.initCloudFirebase)window.initCloudFirebase()}else msg('অ্যাকাউন্ট তৈরি হয়েছে। ইমেইল confirm করে আবার প্রবেশ করুন।')}catch(x){msg(x.message)}}}
  async function start(){if(!U||!K)return;const s=session();if(s?.access_token){window.KORANER_ACCESS_TOKEN=s.access_token;if(s.expires_at&&Date.now()/1000>s.expires_at-60)await refresh();return}if(!await refresh())show()}
  const old=window.onload;window.onload=function(e){start().then(()=>old&&old(e))};window.kaLogout=()=>{localStorage.removeItem(KEY);location.reload()};
})();
