import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const config=window.QURANER_ALO_CONFIG;
const supabase=createClient(config.supabaseUrl,config.supabasePublishableKey,{auth:{autoRefreshToken:true,persistSession:true,detectSessionInUrl:true}});
const $=id=>document.getElementById(id);
const roles=['owner','admin','sub_admin','accounts','teacher','helper','parent','student','viewer'];
const permissions=[['students.view','Students view'],['students.manage','Students manage'],['guardians.view','Guardians view'],['guardians.manage','Guardians manage'],['enrollments.view','Enrollments view'],['enrollments.manage','Enrollments manage'],['teachers.view','Teachers view'],['teachers.manage','Teachers manage'],['staff.view','Helpers/Staff view'],['staff.manage','Helpers/Staff manage'],['attendance.view','Attendance view'],['attendance.manage','Attendance manage'],['quran.view','Quran progress view'],['quran.manage','Quran progress manage'],['fees.view','Fees view'],['fees.manage','Fees manage'],['payments.view','Payments view'],['payments.manage','Payments manage'],['payroll.view','Payroll view'],['payroll.manage','Payroll manage'],['finance.view','Finance view'],['finance.manage','Finance manage'],['accounting.view','Accounting view'],['accounting.manage','Accounting manage'],['vouchers.view','Vouchers manage'],['reports.view','Reports view']];
const manageToView={students.manage:'students.view',guardians.manage:'guardians.view',enrollments.manage:'enrollments.view',teachers.manage:'teachers.view',staff.manage:'staff.view',attendance.manage:'attendance.view',quran.manage:'quran.view',fees.manage:'fees.view',payments.manage:'payments.view',payroll.manage:'payroll.view',finance.manage:'finance.view',accounting.manage:'accounting.view',vouchers.manage:'vouchers.view'};
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
const login=()=>window.location.replace('./');
let access=null;
async function profileFor(session){const {data,error}=await supabase.from('qa_users').select('user_id,email,full_name,role,active').eq('user_id',session.user.id).maybeSingle();if(error)throw error;return data}
async function buildAccess(session,profile){if(['owner','admin'].includes(profile.role))return {session,profile,permissions:new Set(),can:()=>true};const [{data:u,error:ue},{data:r,error:re}]=await Promise.all([supabase.from('qa_user_permissions').select('permission_code').eq('user_id',session.user.id).eq('allowed',true),supabase.from('qa_role_permissions').select('permission_code').eq('role',profile.role)]);if(ue||re)throw ue||re;return {session,profile,permissions:new Set([...(u||[]),...(r||[])].map(x=>x.permission_code)),can:p=>access.permissions.has(p)}}
function roleSelect(role){return `<select data-role>${roles.map(r=>`<option value="${r}" ${r===role?'selected':''}>${r}</option>`).join('')}</select>`}
function permissionCheckboxes(name,selected=[]){return permissions.map(([code,label])=>`<label><input type="checkbox" name="${name}" value="${code}" ${selected.includes(code)?'checked':''}> ${label}</label>`).join('')}
function normalize(name){document.querySelectorAll(`input[name="${name}"]`).forEach(x=>{const v=manageToView[x.value];if(x.checked&&v){const y=document.querySelector(`input[name="${name}"][value="${v}"]`);if(y)y.checked=true}})}
async function countRows(table,fn){let q=supabase.from(table).select('*',{count:'exact',head:true});if(fn)q=fn(q);const {count,error}=await q;if(error)throw error;return count||0}
async function loadMetrics(){const today=new Date().toISOString().slice(0,10);const [s,sa,t,ta,h,ha,a,d]=await Promise.all([countRows('qa_students'),countRows('qa_students',q=>q.not('user_id','is',null)),countRows('qa_teachers'),countRows('qa_teachers',q=>q.not('user_id','is',null)),countRows('qa_staff',q=>q.eq('staff_type','helper')),countRows('qa_staff',q=>q.eq('staff_type','helper').not('user_id','is',null)),countRows('qa_attendance',q=>q.gte('attendance_date',today)),supabase.from('qa_fee_charges').select('current_payable').neq('status','paid')]);$('studentCount').textContent=s;$('teacherCount').textContent=t;$('helperCount').textContent=h;$('attendanceCount').textContent=a;$('feesDue').textContent=`৳ ${(d.data||[]).reduce((x,r)=>x+Number(r.current_payable||0),0).toLocaleString('en-BD',{maximumFractionDigits:0})}`;$('portalActivatedCount').textContent=sa+ta+ha;$('portalActivationMeta').textContent=`Student ${sa}/${s} · Teacher ${ta}/${t} · Helper ${ha}/${h}`;$('studentActivationSummary').textContent=`${sa} / ${s}`;$('studentActivationHint').textContent=s?`${s-sa} জন এখনো activate করেনি`:'কোনো student নেই';$('teacherActivationSummary').textContent=`${ta} / ${t}`;$('teacherActivationHint').textContent=t?`${t-ta} জন এখনো activate করেনি`:'কোনো teacher নেই';$('helperActivationSummary').textContent=`${ha} / ${h}`;$('helperActivationHint').textContent=h?`${h-ha} জন এখনো activate করেনি`:'কোনো helper নেই'}
function addReports(){if(!access.can('reports.view'))return;const box=document.querySelector('.quick-links');if(box&&!box.querySelector('[href="reports.html"]')){const a=document.createElement('a');a.className='quick-link';a.href='reports.html';a.textContent='Reports';box.appendChild(a)}}
function loadPreview(){const box=$('portalPreview');if(!box||access.profile.role!=='owner')return;box.classList.remove('hidden');const msg=$('previewMessage');Promise.all([supabase.from('qa_students').select('student_id,student_code,full_name').eq('status','active').order('student_code'),supabase.from('qa_teachers').select('teacher_id,teacher_code,full_name').eq('active',true).order('teacher_code')]).then(([s,t])=>{if(s.error||t.error){msg.textContent='Preview list load করা যায়নি।';msg.className='message-inline error';return}$('studentPreviewSelect').innerHTML='<option value="">Student নির্বাচন করুন</option>'+(s.data||[]).map(x=>`<option value="${esc(x.student_id)}">${esc(x.student_code)} · ${esc(x.full_name)}</option>`).join('');$('teacherPreviewSelect').innerHTML='<option value="">Teacher নির্বাচন করুন</option>'+(t.data||[]).map(x=>`<option value="${esc(x.teacher_id)}">${esc(x.teacher_code)} · ${esc(x.full_name)}</option>`).join('');msg.textContent=(s.data||[]).length||(t.data||[]).length?'':'এখনো কোনো active Student/Teacher পাওয়া যায়নি।'}).catch(()=>{msg.textContent='Preview list load করা যায়নি।';msg.className='message-inline error'})}
function openPreview(kind){const id=kind==='student'?$('studentPreviewSelect').value:$('teacherPreviewSelect').value;if(!id){$('previewMessage').textContent=kind==='student'?'একজন Student নির্বাচন করুন।':'একজন Teacher নির্বাচন করুন।';return}window.location.href=`${kind==='student'?'student-portal.html?preview_student=':'teacher-portal.html?preview_teacher='}${encodeURIComponent(id)}`}
async function loadUsers(){const {data,error}=await supabase.from('qa_users').select('user_id,email,full_name,role,active').order('created_at');if(error)throw error;const body=$('userRows');body.innerHTML=(data||[]).map(u=>`<tr data-id="${esc(u.user_id)}"><td>${esc(u.email)}</td><td><input data-name value="${esc(u.full_name)}"></td><td>${roleSelect(u.role)}</td><td><select data-active><option value="true" ${u.active?'selected':''}>Active</option><option value="false" ${!u.active?'selected':''}>Inactive</option></select></td><td><button class="save-btn" data-save type="button">Save</button>${u.role==='sub_admin'?'<button class="save-btn secondary" data-permissions type="button">Permissions</button>':''}</td></tr>`).join('');body.querySelectorAll('[data-save]').forEach(b=>b.addEventListener('click',saveUser));body.querySelectorAll('[data-permissions]').forEach(b=>b.addEventListener('click',editPermissions))}
async function saveUser(e){const r=e.currentTarget.closest('tr'),b=e.currentTarget;const id=r.dataset.id,role=r.querySelector('[data-role]').value,active=r.querySelector('[data-active]').value==='true',full_name=r.querySelector('[data-name]').value.trim();b.disabled=true;const {error}=await supabase.from('qa_users').update({full_name,role,active,updated_at:new Date().toISOString()}).eq('user_id',id);b.disabled=false;b.textContent=error?'Failed':'Saved';setTimeout(()=>b.textContent='Save',900)}
function editPermissions(e){const r=e.currentTarget.closest('tr'),id=r.dataset.id;supabase.from('qa_user_permissions').select('permission_code').eq('user_id',id).eq('allowed',true).then(({data,error})=>{if(error)return alert('Permissions load করা যায়নি।');$('existingPermissionTitle').textContent=`Sub Admin permissions — ${r.querySelector('[data-name]').value}`;$('existingPermissions').innerHTML=permissionCheckboxes('existingPerm',(data||[]).map(x=>x.permission_code));$('existingPermissionPanel').dataset.userId=id;$('existingPermissionPanel').classList.remove('hidden');normalize('existingPerm')})}
async function init(){try{const {data:{session}}=await supabase.auth.getSession();if(!session)return login();const p=await profileFor(session);if(!p||!p.active){await supabase.auth.signOut();return login()}access=await buildAccess(session,p);$('rolePill').textContent=(p.role||'viewer').toUpperCase();$('userEmail').textContent=p.email||session.user.email||'';$('loading').classList.add('hidden');$('app').classList.remove('hidden');addReports();loadPreview();loadMetrics().catch(console.error);if(['owner','admin'].includes(p.role)){$('userManagement').classList.remove('hidden');if(p.role==='owner'){$('subAdminPanel').classList.remove('hidden');loadPreview()}loadUsers().catch(console.error)}}catch(e){console.error(e);$('loading').textContent=`Dashboard load করা যায়নি। ${e?.message||'অনুগ্রহ করে আবার login করুন।'}`}}
$('signOut')?.addEventListener('click',async()=>{try{await supabase.auth.signOut()}finally{login()}});$('openStudentPreview')?.addEventListener('click',()=>openPreview('student'));$('openTeacherPreview')?.addEventListener('click',()=>openPreview('teacher'));$('selectAllPermissions')?.addEventListener('click',()=>{document.querySelectorAll('input[name="subPerm"]').forEach(x=>x.checked=true);normalize('subPerm')});$('closePermissionEditor')?.addEventListener('click',()=>{$('existingPermissionPanel').classList.add('hidden')});
init();