import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const config=window.QURANER_ALO_CONFIG;const supabase=createClient(config.supabaseUrl,config.supabasePublishableKey,{auth:{autoRefreshToken:true,persistSession:true,detectSessionInUrl:true}});const $=id=>document.getElementById(id);const ROLE_OPTIONS=['owner','admin','sub_admin','accounts','teacher','helper','parent','student','viewer'];
const MANAGE_TO_VIEW={students.manage:'students.view',guardians.manage:'guardians.view',enrollments.manage:'enrollments.view',teachers.manage:'teachers.view',staff.manage:'staff.view',attendance.manage:'attendance.view',quran.manage:'quran.view',fees.manage:'fees.view',payments.manage:'payments.view',payroll.manage:'payroll.view',finance.manage:'finance.view',accounting.manage:'accounting.view',vouchers.manage:'vouchers.view'};
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));const redirectToLogin=()=>window.location.replace('./');
async function currentProfile(session){const {data,error}=await supabase.from('qa_users').select('user_id,email,full_name,role,active').eq('user_id',session.user.id).maybeSingle();if(error)throw error;return data}
async function logEvent(action,targetUserId=null,meta={}){const actor=(await supabase.auth.getUser()).data.user?.id;const {error}=await supabase.from('qa_audit_log').insert({actor_user_id:actor,action,entity_type:targetUserId?'qa_users':'dashboard',entity_id:targetUserId,metadata:meta});if(error)console.error(error)}
function roleSelect(role){return `<select data-role>${ROLE_OPTIONS.map(r=>`<option value="${r}" ${r===role?'selected':''}>${r}</option>`).join('')}</select>`}
async function loadUsers(){const {data,error}=await supabase.from('qa_users').select('user_id,email,full_name,role,active').order('created_at',{ascending:true});if(error)throw error;const tbody=$('userRows');tbody.innerHTML=(data||[]).map(u=>`<tr data-id="${esc(u.user_id)}"><td>${esc(u.email)}</td><td><input data-name value="${esc(u.full_name)}"></td><td>${roleSelect(u.role)}</td><td><select data-active><option value="true" ${u.active?'selected':''}>Active</option><option value="false" ${!u.active?'selected':''}>Inactive</option></select></td><td><button class="save-btn" data-save type="button">Save</button></td></tr>`).join('');tbody.querySelectorAll('[data-save]').forEach(b=>b.addEventListener('click',saveUser))}
async function saveUser(event){const row=event.currentTarget.closest('tr'),userId=row.dataset.id,fullName=row.querySelector('[data-name]').value.trim(),role=row.querySelector('[data-role]').value,active=row.querySelector('[data-active]').value==='true',button=event.currentTarget;button.disabled=true;button.textContent='Saving…';const {error}=await supabase.from('qa_users').update({full_name:fullName,role,active,updated_at:new Date().toISOString()}).eq('user_id',userId);if(error){alert('এই user update করা যায়নি। Security policy অনুযায়ী অনুমতি না থাকলে পরিবর্তনটি বাতিল হবে।');button.disabled=false;button.textContent='Save'}else{await logEvent('user.profile_updated',userId,{role,active});button.textContent='Saved';setTimeout(()=>{button.textContent='Save';button.disabled=false},900)}}
function selectedSubAdminPermissions(){return [...document.querySelectorAll('input[name="subPerm"]:checked')].map(el=>el.value)}
function normalizePermissionSelection(){document.querySelectorAll('input[name="subPerm"]').forEach(input=>{if(input.checked&&MANAGE_TO_VIEW[input.value]){const view=document.querySelector(`input[name="subPerm"][value="${MANAGE_TO_VIEW[input.value]}"]`);if(view)view.checked=true}})}
async function provisionSubAdmin(event){event.preventDefault();const email=$('subAdminEmail').value.trim().toLowerCase(),fullName=$('subAdminName').value.trim(),password=$('subAdminPassword').value,password2=$('subAdminPassword2').value,msg=$('subAdminMessage');normalizePermissionSelection();const permissions=selectedSubAdminPermissions();if(password!==password2){msg.textContent='দুইটি password একই নয়।';msg.className='message-inline error';return}if(!permissions.length){msg.textContent='কমপক্ষে একটি permission নির্বাচন করুন।';msg.className='message-inline error';return}msg.textContent='Sub Admin account তৈরি হচ্ছে…';msg.className='message-inline';const session=(await supabase.auth.getSession()).data.session;if(!session){redirectToLogin();return}const res=await fetch(`${config.supabaseUrl}/functions/v1/admin-provision`,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${session.access_token}`,'apikey':config.supabasePublishableKey},body:JSON.stringify({email,fullName,password,permissions})});const body=await res.json().catch(()=>({}));if(!res.ok){msg.textContent=body.error==='OWNER_ONLY'?'শুধু Super Admin Sub Admin তৈরি করতে পারবেন।':body.error==='INVALID_INPUT'?'তথ্যগুলো সঠিকভাবে পূরণ করুন।':'Account তৈরি করা যায়নি।';msg.className='message-inline error';return}msg.textContent=`Sub Admin account সফলভাবে তৈরি হয়েছে। ${permissions.length}টি permission দেওয়া হয়েছে।`;msg.className='message-inline success';event.currentTarget.reset();await loadUsers()}
$('selectAllPermissions')?.addEventListener('click',()=>{document.querySelectorAll('input[name="subPerm"]').forEach(el=>el.checked=true)});
document.addEventListener('change',e=>{if(e.target.matches('input[name="subPerm"]'))normalizePermissionSelection()});
async function countRows(table,filter){let query=supabase.from(table).select('*',{count:'exact',head:true});if(filter)query=filter(query);const {count,error}=await query;if(error)throw error;return count??0}
async function loadMetrics(){const [students,teachers,attendance,due]=await Promise.all([countRows('qa_students'),countRows('qa_teachers'),countRows('qa_attendance',q=>q.gte('attendance_date',new Date().toISOString().slice(0,10))),supabase.from('qa_fee_charges').select('current_payable',{count:'exact'}).neq('status','paid')]);$('studentCount').textContent=students;$('teacherCount').textContent=teachers;$('attendanceCount').textContent=attendance;const totalDue=(due.data||[]).reduce((sum,row)=>sum+Number(row.current_payable||0),0);$('feesDue').textContent=`৳ ${totalDue.toLocaleString('en-BD',{maximumFractionDigits:0})}`}
async function init(){const {data:{session}}=await supabase.auth.getSession();if(!session)return redirectToLogin();const profile=await currentProfile(session);if(!profile||profile.active===false){await supabase.auth.signOut();return redirectToLogin()}$('rolePill').textContent=(profile.role||'viewer').toUpperCase();$('userEmail').textContent=profile.email||session.user.email||'';$('loading').classList.add('hidden');$('app').classList.remove('hidden');try{await loadMetrics()}catch(error){console.error(error)}const canManageUsers=profile.role==='owner'||profile.role==='admin';if(canManageUsers){$('userManagement').classList.remove('hidden');if(profile.role==='owner'){$('subAdminPanel').classList.remove('hidden');$('subAdminForm').addEventListener('submit',provisionSubAdmin)}try{await loadUsers()}catch(error){console.error(error)}}}
$('signOut').addEventListener('click',async()=>{await supabase.auth.signOut();redirectToLogin()});supabase.auth.onAuthStateChange((event,session)=>{if((event==='SIGNED_OUT'||!session)&&document.visibilityState!=='hidden')redirectToLogin()});init().catch(error=>{console.error(error);$('loading').textContent='Dashboard load করা যায়নি। আবার login করুন।'});