import {createClient} from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
import {getAccess} from './authz.js';
const c=window.QURANER_ALO_CONFIG;const supabase=createClient(c.supabaseUrl,c.supabasePublishableKey,{auth:{autoRefreshToken:true,persistSession:true,detectSessionInUrl:true}});const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>\"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[ch]));let access=null,students=[],teachers=[];
function msg(text,type=''){ $('formMessage').textContent=text;$('formMessage').className=`message-inline ${type}`.trim(); }
function setFormEnabled(enabled){$('enrollmentForm').querySelectorAll('input,select,textarea,button[type="submit"]').forEach(x=>x.disabled=!enabled)}
async function loadLists(){const [{data:s,error:se},{data:t,error:te}]=await Promise.all([supabase.from('qa_students').select('student_id,student_code,full_name').order('full_name'),supabase.from('qa_teachers').select('teacher_id,teacher_code,full_name,user_id').eq('active',true).order('full_name')]);if(se||te)throw new Error('LIST_LOAD');students=s||[];teachers=(t||[]).filter(x=>x.user_id);$('studentSelect').innerHTML='<option value="">Student নির্বাচন করুন</option>'+students.map(x=>`<option value="${esc(x.student_id)}">${esc(x.student_code)} · ${esc(x.full_name)}</option>`).join('');$('teacherUser').innerHTML='<option value="">— নির্ধারিত নয় —</option>'+teachers.map(x=>`<option value="${esc(x.user_id)}">${esc(x.teacher_code)} · ${esc(x.full_name)}</option>`).join('')}
async function loadRows(){const {data,error}=await supabase.from('qa_enrollments').select('enrollment_id,student_id,course_code,start_date,end_date,status,teacher_user_id,notes').order('created_at',{ascending:false}).limit(300);if(error)throw error;const sm=Object.fromEntries(students.map(x=>[x.student_id,`${x.student_code} · ${x.full_name}`]));const tm=Object.fromEntries(teachers.map(x=>[x.user_id,`${x.teacher_code} · ${x.full_name}`]));$('countLabel').textContent=`${(data||[]).length} records`;$('rows').innerHTML=(data||[]).map(x=>`<tr><td>${esc(sm[x.student_id]||x.student_id)}</td><td><strong>${esc(x.course_code)}</strong></td><td>${esc(x.start_date)}</td><td>${esc(x.end_date||'—')}</td><td>${esc(tm[x.teacher_user_id]||'—')}</td><td><span class="active-badge ${x.status==='active'?'on':'off'}">${esc(x.status)}</span></td></tr>`).join('')||'<tr><td colspan="6">কোনো enrollment নেই।</td></tr>'}
async function init(){access=await getAccess(supabase);if(!access){await supabase.auth.signOut();location.replace('./');return;}if(!access.can('enrollments.view')&&!access.can('enrollments.manage')){$('loading').textContent='Enrollments module-এর permission আপনার account-এ নেই।';return;}setFormEnabled(access.can('enrollments.manage'));$('startDate').value=new Date().toISOString().slice(0,10);await loadLists();await loadRows();$('loading').classList.add('hidden');$('app').classList.remove('hidden')}
$('enrollmentForm').addEventListener('submit',async e=>{e.preventDefault();if(!access?.can('enrollments.manage'))return msg('Enrollments manage permission নেই।','error');const row={student_id:$('studentSelect').value,course_code:$('courseCode').value.trim(),start_date:$('startDate').value,end_date:$('endDate').value||null,status:$('status').value,teacher_user_id:$('teacherUser').value||null,notes:$('notes').value.trim()};if(!row.student_id||!row.course_code)return msg('Student ও course অবশ্যই দিতে হবে।','error');if(row.end_date&&row.end_date<row.start_date)return msg('End date, Start date-এর আগে হতে পারে না।','error');const {error}=await supabase.from('qa_enrollments').insert(row);if(error)return msg('Enrollment save করা যায়নি।','error');msg('Enrollment সফলভাবে যুক্ত হয়েছে।','success');e.target.reset();$('startDate').value=new Date().toISOString().slice(0,10);await loadRows()});
$('signOut').addEventListener('click',async()=>{await supabase.auth.signOut();location.replace('./')});init().catch(e=>{console.error(e);$('loading').textContent='Enrollment page load করা যায়নি।'})