import {createClient} from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
import {getAccess} from './authz.js';
const c=window.QURANER_ALO_CONFIG;const supabase=createClient(c.supabaseUrl,c.supabasePublishableKey,{auth:{autoRefreshToken:true,persistSession:true,detectSessionInUrl:true}});const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
const today=()=>new Date().toISOString().slice(0,10);const safeFile=v=>String(v||'ALL').replace(/[^a-z0-9_-]+/gi,'_').replace(/^_+|_+$/g,'').slice(0,50)||'ALL';
let access=null,state={students:[],teachers:[],groups:[]},current=[];
function setMessage(text,type=''){const el=$('message');el.textContent=text;el.className=`message-inline ${type}`.trim();}
function normStatus(value){return typeof value==='boolean'?(value?'active':'inactive'):String(value||'').toLowerCase();}
function groupList(rows){return [...new Set(rows.flatMap(x=>x.groups||[]).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'en'));}
async function loadSource(){setMessage('Live data load হচ্ছে…');const wantStudents=access.can('students.view')||access.can('students.manage');const wantTeachers=access.can('teachers.view')||access.can('teachers.manage');const [{data:students,error:se},{data:teachers,error:te},{data:enrollments,error:ee}]=await Promise.all([
  wantStudents?supabase.from('qa_students').select('student_id,student_code,full_name,full_name_bn,status,phone,email').order('student_code',{ascending:true}):Promise.resolve({data:[],error:null}),
  wantTeachers?supabase.from('qa_teachers').select('teacher_id,teacher_code,full_name,full_name_bn,phone,email,specialization,active').order('teacher_code',{ascending:true}):Promise.resolve({data:[],error:null}),
  supabase.from('qa_enrollments').select('student_id,teacher_user_id,course_code,status,start_date,end_date').order('start_date',{ascending:false})
]);
if(se||te||ee)throw se||te||ee;
const teacherIds=(teachers||[]).map(t=>t.teacher_id);let teacherUsers={};if(teacherIds.length){const teacherUserRows=(teachers||[]).map(t=>({id:t.teacher_id,user_id:t.user_id}));teacherUsers=Object.fromEntries(teacherUserRows.filter(x=>x.user_id).map(x=>[x.id,x.user_id]));}
const teacherById=Object.fromEntries((teachers||[]).map(t=>[t.teacher_id,t]));
const studentById=Object.fromEntries((students||[]).map(s=>[s.student_id,s]));
const studentGroups={};const teacherGroups={};
(enrollments||[]).filter(x=>x.status==='active'&&x.course_code).forEach(x=>{if(studentById[x.student_id]){(studentGroups[x.student_id]??=[]).push(x.course_code);}const teacher=teacherById[Object.keys(teacherById).find(id=>teacherUsers[id]===x.teacher_user_id)];if(teacher)(teacherGroups[teacher.teacher_id]??=[]).push(x.course_code);});
state.students=(students||[]).map(s=>({...s,groups:[...new Set(studentGroups[s.student_id]||[])].sort()}));state.teachers=(teachers||[]).map(t=>({...t,groups:[...new Set(teacherGroups[t.teacher_id]||[])].sort()}));state.groups=[...new Set([...groupList(state.students),...groupList(state.teachers)])].sort((a,b)=>a.localeCompare(b,'en'));populateGroups();setMessage('');render();}
function populateGroups(){const type=$('entityType').value;const rows=state[type]||[];const groups=groupList(rows);const select=$('groupFilter');select.innerHTML='<option value="all">All Groups / Courses</option>'+(rows.some(x=>!(x.groups||[]).length)?'<option value="__none">Unassigned / No active group</option>':'')+groups.map(g=>`<option value="${esc(g)}">${esc(g)}</option>`).join('');}
function filteredRows(){const type=$('entityType').value,status=$('statusFilter').value,group=$('groupFilter').value;let rows=(state[type]||[]).filter(r=>status==='all'||normStatus(type==='teachers'?r.active:r.status)===status);if(group==='__none')rows=rows.filter(r=>!(r.groups||[]).length);else if(group!=='all')rows=rows.filter(r=>(r.groups||[]).includes(group));return rows;}
function buildRecords(){const type=$('entityType').value;return filteredRows().map(r=>type==='students'?{
  'Student ID':r.student_code,'Student Name':r.full_name_bn||r.full_name||'','Phone':r.phone||'','Email':r.email||'','Status':r.status||'','Group / Course':(r.groups||[]).join(', ')||'Unassigned'
}:{'Teacher ID':r.teacher_code,'Teacher Name':r.full_name_bn||r.full_name||'','Phone':r.phone||'','Email':r.email||'','Specialization':r.specialization||'','Status':r.active?'Active':'Inactive','Group / Course':(r.groups||[]).join(', ')||'Unassigned'});}
function groupSummary(records){const map=new Map();records.forEach(r=>{const groups=String(r['Group / Course']||'Unassigned').split(', ').filter(Boolean);groups.forEach(g=>map.set(g,(map.get(g)||0)+1));});return [...map.entries()].sort((a,b)=>a[0].localeCompare(b[0],'en')).map(([group,count])=>({'Group / Course':group,'Records':count}));}
function render(){const type=$('entityType').value,records=buildRecords();current=records;const head=$('tableHead'),body=$('tableBody');const keys=records.length?Object.keys(records[0]):type==='students'?['Student ID','Student Name','Phone','Email','Status','Group / Course']:['Teacher ID','Teacher Name','Phone','Email','Specialization','Status','Group / Course'];head.innerHTML='<tr>'+keys.map(k=>`<th>${esc(k)}</th>`).join('')+'</tr>';body.innerHTML=records.length?records.map(row=>'<tr>'+keys.map(k=>`<td>${esc(row[k])}</td>`).join('')+'</tr>').join(''):`<tr><td colspan="${keys.length}">এই filter অনুযায়ী কোনো record পাওয়া যায়নি।</td></tr>`;$('recordCount').textContent=records.length;$('groupCount').textContent=new Set(records.flatMap(r=>String(r['Group / Course']||'Unassigned').split(', ').filter(Boolean))).size;$('generatedDate').textContent=today();const group=$('groupFilter').selectedOptions[0]?.textContent||'All Groups / Courses';const status=$('statusFilter').selectedOptions[0]?.textContent||'All Status';const label=type==='students'?'Student List':'Teacher List';$('printHeading').textContent=label;$('printCriteria').textContent=`Group / Course: ${group} · Status: ${status} · Records: ${records.length} · Generated: ${today()}`;}
function downloadExcel(){if(!window.XLSX){setMessage('Excel library load হয়নি। আবার চেষ্টা করুন।','error');return;}const type=$('entityType').value,records=current;const label=type==='students'?'Students':'Teachers',group=$('groupFilter').selectedOptions[0]?.textContent||'All';const ws=XLSX.utils.json_to_sheet(records.length?records:[{Info:'No records found for selected filters.'}]);const summary=XLSX.utils.json_to_sheet(groupSummary(records));const meta=XLSX.utils.aoa_to_sheet([['QURANER ALO','List Export'],['List Type',label],['Group / Course',group],['Status',$('statusFilter').selectedOptions[0]?.textContent||'All Status'],['Generated',today()],['Records',records.length]]);ws['!cols']=(records.length?Object.keys(records[0]):['Info']).map(k=>({wch:Math.min(34,Math.max(14,k.length+4))}));summary['!cols']=[{wch:28},{wch:14}];meta['!cols']=[{wch:20},{wch:40}];const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,label.slice(0,31));XLSX.utils.book_append_sheet(wb,summary,'Group Summary');XLSX.utils.book_append_sheet(wb,meta,'Export Info');const file=`QuranerAlo_${label}_${safeFile($('groupFilter').value)}_${today()}.xlsx`;XLSX.writeFile(wb,file);setMessage(`Excel ফাইল তৈরি হয়েছে: ${file}`,'success');}
function printPdf(){render();window.print();}
$('entityType').addEventListener('change',()=>{populateGroups();render();});$('groupFilter').addEventListener('change',render);$('statusFilter').addEventListener('change',render);$('refreshData').addEventListener('click',()=>loadSource().catch(e=>{console.error(e);setMessage('Live data load করা যায়নি।','error');}));$('downloadExcel').addEventListener('click',downloadExcel);$('printPdf').addEventListener('click',printPdf);$('signOut').addEventListener('click',async()=>{await supabase.auth.signOut();location.replace('./');});
async function init(){access=await getAccess(supabase);if(!access){await supabase.auth.signOut();location.replace('./');return;}if(!access.can('students.view')&&!access.can('students.manage')&&!access.can('teachers.view')&&!access.can('teachers.manage')){$('loading').textContent='Student/Teacher list export-এর জন্য view permission প্রয়োজন।';return;}if(!(access.can('students.view')||access.can('students.manage'))){$('entityType').value='teachers';$('entityType').querySelector('option[value="students"]').disabled=true;}if(!(access.can('teachers.view')||access.can('teachers.manage'))){$('entityType').querySelector('option[value="teachers"]').disabled=true;}await loadSource();$('loading').classList.add('hidden');$('app').classList.remove('hidden');}
init().catch(e=>{console.error(e);$('loading').textContent='Export page load করা যায়নি।';});