import {createClient} from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const c=window.QURANER_ALO_CONFIG;const supabase=createClient(c.supabaseUrl,c.supabasePublishableKey,{auth:{autoRefreshToken:true,persistSession:true,detectSessionInUrl:true}});const $=id=>document.getElementById(id);
function esc(v){return String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));}function money(v){return Number(v||0).toFixed(2)}function msg(id,t,type=''){ $(id).textContent=t;$(id).className=`message-inline ${type}`.trim();}
function today(){return new Date().toISOString().slice(0,10)}
async function init(){const {data:{session}}=await supabase.auth.getSession();if(!session){location.replace('./');return;}const {data:p,error:pe}=await supabase.from('qa_users').select('role,active').eq('user_id',session.user.id).maybeSingle();if(pe||!p||!p.active){await supabase.auth.signOut();location.replace('./');return;}$('transactionDate').value=today();$('voucherDate').value=today();$('loading').classList.add('hidden');$('app').classList.remove('hidden');await refresh();}
async function refresh(){const [{data:tx,error:te},{data:v,error:ve}]=await Promise.all([supabase.from('qa_finance_transactions').select('transaction_id,transaction_date,direction,category,amount,account_name,reference,description').order('transaction_date',{ascending:false}).limit(200),supabase.from('qa_vouchers').select('voucher_id,voucher_no,voucher_type,voucher_date,amount,account_name,party_name,status').order('created_at',{ascending:false}).limit(200)]);if(te||ve){msg('financeMessage','Finance data load করা যায়নি।','error');return;}tx=tx||[];v=v||[];const income=tx.filter(x=>x.direction==='income').reduce((a,x)=>a+Number(x.amount||0),0),expense=tx.filter(x=>x.direction==='expense').reduce((a,x)=>a+Number(x.amount||0),0);$('incomeTotal').textContent=`৳${money(income)}`;$('expenseTotal').textContent=`৳${money(expense)}`;$('netTotal').textContent=`৳${money(income-expense)}`;$('voucherTotal').textContent=v.length;$('financeRows').innerHTML=tx.map(x=>`<tr><td>${esc(x.transaction_date)}</td><td>${esc(x.direction)}</td><td>${esc(x.category)}</td><td>৳${money(x.amount)}</td><td>${esc(x.account_name)}</td><td>${esc(x.reference||'—')}</td></tr>`).join('');$('voucherRows').innerHTML=v.map(x=>`<tr><td><strong>${esc(x.voucher_no)}</strong></td><td>${esc(x.voucher_date)}</td><td>${esc(x.voucher_type)}</td><td>৳${money(x.amount)}</td><td>${esc(x.party_name||'—')}</td><td>${esc(x.status)}</td></tr>`).join('');}
$('financeForm').addEventListener('submit',async e=>{e.preventDefault();msg('financeMessage','Saving…');const row={transaction_date:$('transactionDate').value,direction:$('direction').value,category:$('category').value.trim(),amount:+$('amount').value,account_name:$('accountName').value,reference:$('reference').value.trim()||null,description:$('description').value.trim()};const {error}=await supabase.from('qa_finance_transactions').insert(row);if(error){msg('financeMessage','Transaction save করা যায়নি।','error');return;}msg('financeMessage','Transaction successfully saved।','success');e.target.reset();$('transactionDate').value=today();await refresh();});
$('voucherForm').addEventListener('submit',async e=>{e.preventDefault();msg('voucherMessage','Creating voucher…');const {data:vn,error:ve}=await supabase.rpc('qa_next_voucher_no',{p_type:$('voucherType').value});if(ve){msg('voucherMessage','Voucher number generate করা যায়নি।','error');return;}const voucherNo=vn;const row={voucher_no:voucherNo,voucher_type:$('voucherType').value,voucher_date:$('voucherDate').value,amount:+$('voucherAmount').value,account_name:$('voucherAccount').value,party_name:$('partyName').value.trim(),reference:$('voucherReference').value.trim()||null,description:$('voucherDescription').value.trim()};const {error}=await supabase.from('qa_vouchers').insert(row);if(error){msg('voucherMessage','Voucher save করা যায়নি।','error');return;}msg('voucherMessage',`Voucher তৈরি হয়েছে: ${voucherNo}`,'success');e.target.reset();$('voucherDate').value=today();await refresh();});
$('signOut').addEventListener('click',async()=>{await supabase.auth.signOut();location.replace('./');});init();
