import {createClient} from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
import { getAccess } from './authz.js';
const c=window.QURANER_ALO_CONFIG;const supabase=createClient(c.supabaseUrl,c.supabasePublishableKey,{auth:{autoRefreshToken:true,persistSession:true,detectSessionInUrl:true}});const $=id=>document.getElementById(id);
function esc(v){return String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));}function money(v){return Number(v||0).toFixed(2)}function msg(id,t,type=''){ $(id).textContent=t;$(id).className=`message-inline ${type}`.trim();}
function today(){return new Date().toISOString().slice(0,10)}
function setFormEnabled(formId,enabled){$(formId).querySelectorAll('input,select,textarea,button[type="submit"]').forEach(el=>el.disabled=!enabled)}
let canFinanceView=false;let canFinanceManage=false;let canVoucherView=false;let canVoucherManage=false;
async function init(){const access=await getAccess(supabase);if(!access){await supabase.auth.signOut();location.replace('./');return;}canFinanceView=access.can('finance.view')||access.can('finance.manage');canFinanceManage=access.can('finance.manage');canVoucherView=access.can('vouchers.view')||access.can('vouchers.manage');canVoucherManage=access.can('vouchers.manage');if(!canFinanceView&&!canVoucherView){$('loading').textContent='Finance/Voucher module-এর permission আপনার account-এ নেই।';return;}setFormEnabled('financeForm',canFinanceManage);setFormEnabled('voucherForm',canVoucherManage);$('transactionDate').value=today();$('voucherDate').value=today();$('loading').classList.add('hidden');$('app').classList.remove('hidden');await refresh();}
async function refresh(){const txPromise=canFinanceView?supabase.from('qa_finance_transactions').select('transaction_id,transaction_date,direction,category,amount,account_name,reference,description').order('transaction_date',{ascending:false}).limit(200):Promise.resolve({data:[],error:null});const voucherPromise=canVoucherView?supabase.from('qa_vouchers').select('voucher_id,voucher_no,voucher_type,voucher_date,amount,account_name,party_name,status').order('created_at',{ascending:false}).limit(200):Promise.resolve({data:[],error:null});const [{data:tx,error:te},{data:v,error:ve}]=await Promise.all([txPromise,voucherPromise]);if(te||ve){msg('financeMessage','Finance/Voucher data load করা যায়নি।','error');return;}const txs=tx||[];const vs=v||[];const income=txs.filter(x=>x.direction==='income').reduce((a,x)=>a+Number(x.amount||0),0),expense=txs.filter(x=>x.direction==='expense').reduce((a,x)=>a+Number(x.amount||0),0);$('incomeTotal').textContent=canFinanceView?`৳${money(income)}`:'—';$('expenseTotal').textContent=canFinanceView?`৳${money(expense)}`:'—';$('netTotal').textContent=canFinanceView?`৳${money(income-expense)}`:'—';$('voucherTotal').textContent=canVoucherView?vs.length:'—';$('financeRows').innerHTML=txs.map(x=>`<tr><td>${esc(x.transaction_date)}</td><td>${esc(x.direction)}</td><td>${esc(x.category)}</td><td>৳${money(x.amount)}</td><td>${esc(x.account_name)}</td><td>${esc(x.reference||'—')}</td></tr>`).join('')||'<tr><td colspan="6">No finance records available for this permission set.</td></tr>';$('voucherRows').innerHTML=vs.map(x=>`<tr><td><strong>${esc(x.voucher_no)}</strong></td><td>${esc(x.voucher_date)}</td><td>${esc(x.voucher_type)}</td><td>৳${money(x.amount)}</td><td>${esc(x.party_name||'—')}</td><td>${esc(x.status)}</td></tr>`).join('')||'<tr><td colspan="6">No voucher records available for this permission set.</td></tr>';}
$('financeForm').addEventListener('submit',async e=>{e.preventDefault();if(!canFinanceManage){msg('financeMessage','Finance manage permission নেই।','error');return;}msg('financeMessage','Saving…');const row={transaction_date:$('transactionDate').value,direction:$('direction').value,category:$('category').value.trim(),amount:+$('amount').value,account_name:$('accountName').value,reference:$('reference').value.trim()||null,description:$('description').value.trim()};const {error}=await supabase.from('qa_finance_transactions').insert(row);if(error){msg('financeMessage','Transaction save করা যায়নি।','error');return;}msg('financeMessage','Transaction successfully saved।','success');e.target.reset();$('transactionDate').value=today();await refresh();});
$('voucherForm').addEventListener('submit',async e=>{e.preventDefault();if(!canVoucherManage){msg('voucherMessage','Vouchers manage permission নেই।','error');return;}msg('voucherMessage','Creating voucher…');const {data:vn,error:ve}=await supabase.rpc('qa_next_voucher_no',{p_type:$('voucherType').value});if(ve){msg('voucherMessage','Voucher number generate করা যায়নি।','error');return;}const voucherNo=vn;const row={voucher_no:voucherNo,voucher_type:$('voucherType').value,voucher_date:$('voucherDate').value,amount:+$('voucherAmount').value,account_name:$('voucherAccount').value,party_name:$('partyName').value.trim(),reference:$('voucherReference').value.trim()||null,description:$('voucherDescription').value.trim()};const {error}=await supabase.from('qa_vouchers').insert(row);if(error){msg('voucherMessage','Voucher save করা যায়নি。','error');return;}msg('voucherMessage',`Voucher তৈরি হয়েছে: ${voucherNo}`,'success');e.target.reset();$('voucherDate').value=today();await refresh();});
$('signOut').addEventListener('click',async()=>{await supabase.auth.signOut();location.replace('./');});init();
