import {createClient} from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
import {getAccess} from './authz.js';
const c=window.QURANER_ALO_CONFIG;const supabase=createClient(c.supabaseUrl,c.supabasePublishableKey,{auth:{autoRefreshToken:true,persistSession:true,detectSessionInUrl:true}});const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>\"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[ch]));let access=null,guardians=[],students=[],links=[];
function msg(id,text,type=''){ $(id).textContent=text;$(id).className=`message-inline ${type}`.trim(); }
function setFormEnabled(id,enabled){$(id).querySelectorAll('input,select,textarea,button[type="submit"]').forEach(x=>x.disabled=!enabled)}
async function loadGuardians(){const {data,error}=await supabase.from('qa_guardians').select('guardian_id,full_name,relation,phone,email,address').order('full_name');if(error)throw error;guardians=data||[];const {data:l,error:le}=await supabase.from('qa_student_guardians').select('student_id,guardian_id,is_primary');if(le)throw le;links=l||[];const names=Object.fromEntries((students||[]).map(s=>[s.student_id,`${s.student_code} · ${s.full_name}`]));$('guardianSelect').innerHTML='<option value="">Guardian নির্বাচন করুন</option>'+guardians.map(g=>`<option value="${esc(g.guardian_id)}">${esc(g.full_name)} · ${esc(g.relation)}</option>`).join('');$('guardianRows').innerHTML=guardians.map(g=>{const mine=links.filter(x=>x.guardian_id===g.guardian_id);const text=mine.map(x=>`${esc(names[x.student_id]||x.student_id)}${x.is_primary?' ★':''}`).join('<br>')||'—';return `<tr><td><strong>${esc(g.full_name)}</strong></td><td>${esc(g.relation)}</td><td>${esc(g.phone)}</td><td>${esc(g.email)}</td><td>${text}</td></tr>`}).join('')||'<tr><td colspan="5">কোনো guardian নেই।</td></tr>';$('countLabel').textContent=`${guardians.length} records`}
async function loadStudents(){const {data,error}=await supabase.from('qa_students').select('student_id,student_code,full_name').order('full_name');if(error)throw error;students=data||[];$('studentSelect').innerHTML='<option value="">Student নির্বাচন করুন</option>'+students.map(s=>`<option value="${esc(s.student_id)}">${esc(s.student_code)} · ${esc(s.full_name)}</option>`).join('')}
async function init(){access=await getAccess(supabase);if(!access){await supabase.auth.signOut();location.replace('./');return;}const canView=access.can('guardians.view')||access.can('guardians.manage')||access.can('students.view')||access.can('students.manage');if(!canView){$('loading').textContent='Guardians module-এর permission আপনার account-এ নেই।';return;}const canGuardianManage=access.can('guardians.manage');const canLink=canGuardianManage&&(access.can('students.manage'));setFormEnabled('guardianForm',canGuardianManage);setFormEnabled('linkForm',canLink);$('linkPermission').textContent=canLink?'GUARDIANS.MANAGE + STUDENTS.MANAGE': 'লিংক করতে guardian ও student দুইটির manage permission প্রয়োজন';await loadStudents();await loadGuardians();$('loading').classList.add('hidden');$('app').classList.remove('hidden')}
$('guardianForm').addEventListener('submit',async e=>{e.preventDefault();if(!access?.can('guardians.manage'))return msg('formMessage','Guardians manage permission নেই।','error');const row={full_name:$('fullName').value.trim(),relation:$('relation').value.trim(),phone:$('phone').value.trim(),email:$('email').value.trim(),address:$('address').value.trim()};const {error}=await supabase.from('qa_guardians').insert(row);if(error)return msg('formMessage','Guardian save করা যায়নি।','error');msg('formMessage','Guardian সফলভাবে যুক্ত হয়েছে।','success');e.target.reset();await loadGuardians()});
$('linkForm').addEventListener('submit',async e=>{e.preventDefault();if(!(access?.can('guardians.manage')&&access?.can('students.manage')))return msg('linkMessage','Guardian + Student manage permission দুটিই প্রয়োজন।','error');const row={guardian_id:$('guardianSelect').value,student_id:$('studentSelect').value,is_primary:$('isPrimary').value==='true'};if(!row.guardian_id||!row.student_id)return msg('linkMessage','Guardian এবং Student নির্বাচন করুন।','error');const {error}=await supabase.from('qa_student_guardians').upsert(row,{onConflict:'student_id,guardian_id'});if(error)return msg('linkMessage','Student link save করা যায়নি।','error');msg('linkMessage','Guardian-Student link সফল হয়েছে।','success');await loadGuardians()});
$('signOut').addEventListener('click',async()=>{await supabase.auth.signOut();location.replace('./')});init().catch(e=>{console.error(e);$('loading').textContent='Guardians page load করা যায়নি।'})