import {createClient} from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
import { getAccess } from './authz.js';
const c=window.QURANER_ALO_CONFIG;const supabase=createClient(c.supabaseUrl,c.supabasePublishableKey,{auth:{autoRefreshToken:true,persistSession:true,detectSessionInUrl:true}});const $=id=>document.getElementById(id);let employees=[];let employeeMap={};let payroll=[];let canManage=false;
function esc(v){return String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));}function money(v){return Number(v||0).toFixed(2)}function msg(t,type=''){ $('message').textContent=t;$('message').className=`message-inline ${type}`.trim();}
function calc(){const basic=+($('basic').value||0),a=+($('allowance').value||0),b=+($('bonus').value||0),o=+($('overtime').value||0),d=+($('deduction').value||0),l=+($('leaveDeduction').value||0),ad=+($('advance').value||0),adj=+($('adjustment').value||0);$('net').textContent=money(basic+a+b+o+adj-d-l-ad);return basic+a+b+o+adj-d-l-ad;}
function setFormEnabled(enabled){$('payrollForm').querySelectorAll('input,select,textarea,button[type="submit"]').forEach(el=>el.disabled=!enabled)}
async function init(){const access=await getAccess(supabase);if(!access){await supabase.auth.signOut();location.replace('./');return;}canManage=access.can('payroll.manage');if(!access.can('payroll.view')&&!canManage){$('loading').textContent='Payroll module-এর permission আপনার account-এ নেই।';return;}setFormEnabled(canManage);const [{data:t,error:te},{data:s,error:se}]=await Promise.all([supabase.from('qa_teachers').select('user_id,teacher_code,full_name').eq('active',true).order('full_name'),supabase.from('qa_staff').select('user_id,staff_code,full_name,staff_type').eq('active',true).order('full_name')]);if(te||se){msg('Employee list load করা যায়নি।','error');return;}employees=[...(t||[]).map(x=>({...x,code:x.teacher_code,type:'Teacher'})),...(s||[]).map(x=>({...x,code:x.staff_code,type:x.staff_type||'Staff'}))];employeeMap=Object.fromEntries(employees.map(x=>[x.user_id,`${x.code} · ${x.full_name} (${x.type})`]));$('employeeSelect').innerHTML='<option value="">Employee নির্বাচন করুন</option>'+employees.map(x=>`<option value="${esc(x.user_id)}">${esc(x.code)} · ${esc(x.full_name)} (${esc(x.type)})</option>`).join('');$('payrollMonth').value=new Date().toISOString().slice(0,7);$('loading').classList.add('hidden');$('app').classList.remove('hidden');await refresh();}
async function refresh(){const {data,error}=await supabase.from('qa_payroll_records').select('payroll_id,employee_user_id,payroll_month,basic,allowance,bonus,overtime,deduction,leave_deduction,advance,adjustment,net_payable,status,paid_at,payment_method,payment_reference,notes').order('payroll_month',{ascending:false}).limit(200);if(error){msg('Payroll ledger load করা যায়নি।','error');return;}payroll=data||[];$('count').textContent=`${payroll.length} records`;$('rows').innerHTML=payroll.map(x=>{const adds=Number(x.allowance)+Number(x.bonus)+Number(x.overtime);const reductions=Number(x.deduction)+Number(x.leave_deduction)+Number(x.advance);return `<tr><td>${esc(x.payroll_month)}</td><td>${esc(employeeMap[x.employee_user_id]||x.employee_user_id)}</td><td>৳${money(x.basic)}</td><td>৳${money(adds)}</td><td>৳${money(reductions)}</td><td><strong>৳${money(x.net_payable)}</strong></td><td><select class="status-select" data-id="${esc(x.payroll_id)}" ${canManage?'':'disabled'}><option ${x.status==='draft'?'selected':''}>draft</option><option ${x.status==='reviewed'?'selected':''}>reviewed</option><option ${x.status==='approved'?'selected':''}>approved</option><option ${x.status==='paid'?'selected':''}>paid</option><option ${x.status==='cancelled'?'selected':''}>cancelled</option></select></td><td><button class="save-btn" data-save="${esc(x.payroll_id)}" ${canManage?'':'disabled'}>Save</button></td></tr>`}).join('');document.querySelectorAll('[data-save]').forEach(btn=>btn.addEventListener('click',()=>updateStatus(btn.dataset.save)));}
async function updateStatus(id){if(!canManage){msg('Payroll manage permission নেই।','error');return;}const select=document.querySelector(`[data-id="${CSS.escape(id)}"]`);const status=select?.value;if(!status)return;const patch={status};if(status==='paid')patch.paid_at=new Date().toISOString();const {error}=await supabase.from('qa_payroll_records').update(patch).eq('payroll_id',id);if(error){msg('Payroll status update করা যায়নি।','error');return;}msg('Payroll status updated।','success');await refresh();}
['basic','allowance','bonus','overtime','deduction','leaveDeduction','advance','adjustment'].forEach(id=>$(id).addEventListener('input',calc));
$('payrollForm').addEventListener('submit',async e=>{e.preventDefault();if(!canManage){msg('Payroll manage permission নেই।','error');return;}msg('Saving…');const row={employee_user_id:$('employeeSelect').value,payroll_month:`${$('payrollMonth').value}-01`,basic:+($('basic').value||0),allowance:+($('allowance').value||0),bonus:+($('bonus').value||0),overtime:+($('overtime').value||0),deduction:+($('deduction').value||0),leave_deduction:+($('leaveDeduction').value||0),advance:+($('advance').value||0),adjustment:+($('adjustment').value||0),notes:$('notes').value.trim()};const {error}=await supabase.from('qa_payroll_records').insert(row);if(error){msg(error.code==='23505'?'এই employee-এর এই মাসের payroll record আগে থেকেই আছে।':'Payroll save করা যায়নি।','error');return;}msg('Payroll record সফলভাবে save হয়েছে।','success');e.target.reset();$('payrollMonth').value=new Date().toISOString().slice(0,7);calc();await refresh();});
$('signOut').addEventListener('click',async()=>{await supabase.auth.signOut();location.replace('./');});init();
