import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
import { getAccess } from './authz.js';
const c=window.QURANER_ALO_CONFIG;const supabase=createClient(c.supabaseUrl,c.supabasePublishableKey,{auth:{autoRefreshToken:true,persistSession:true,detectSessionInUrl:true}});const $=id=>document.getElementById(id);
function esc(v){return String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));}function msg(t,type=''){ $('message').textContent=t;$('message').className=`message-inline ${type}`.trim();}
let access=null;let canWrite=false;
async function init(){access=await getAccess(supabase);if(!access){await supabase.auth.signOut();location.replace('./');return;}canWrite=access.can('quran.manage');if(!access.can('quran.view')&&!canWrite){$('loading').textContent='Quran Progress module-এর permission আপনার account-এ নেই।';return;}
if(!canWrite){$('progressForm').querySelectorAll('input,select,textarea,button[type="submit"]').forEach(e=>e.disabled=true);msg('আপনার account-এ Quran progress edit permission নেই।','error');}
const [s,t]=await Promise.all([supabase.from('qa_students').select('student_id,student_code,full_name').eq('status','active').order('full_name'),supabase.from('qa_teachers').select('teacher_id,teacher_code,full_name').eq('active',true).order('full_name')]);if(s.error||t.error){msg('Student/Teacher list load করা যায়নি।','error');return;}$('studentSelect').innerHTML='<option value="">Student নির্বাচন করুন</option>'+s.data.map(x=>`<option value="${esc(x.student_id)}">${esc(x.student_code)} · ${esc(x.full_name)}</option>`).join('');$('teacherSelect').innerHTML='<option value="">— নির্ধারিত নয় —</option>'+t.data.map(x=>`<option value="${esc(x.teacher_id)}">${esc(x.teacher_code)} · ${esc(x.full_name)}</option>`).join('');$('lessonDate').value=new Date().toISOString().slice(0,10);$('loading').classList.add('hidden');$('app').classList.remove('hidden');await loadRecent();}
async function loadRecent(){const {data,error}=await supabase.from('qa_quran_progress').select('progress_id,lesson_date,student_id,track,surah_name,juz_number,ayah_from,ayah_to,page_number,completion_percent,next_target').order('lesson_date',{ascending:false}).limit(50);if(error){msg('Quran progress load করা যায়নি।','error');return;}const ids=[...new Set(data.map(x=>x.student_id))];let names={};if(ids.length){const {data:s}=await supabase.from('qa_students').select('student_id,student_code,full_name').in('student_id',ids);names=Object.fromEntries((s||[]).map(x=>[x.student_id,`${x.student_code} · ${x.full_name}`]));}$('countLabel').textContent=`${data.length} entries`;$('progressRows').innerHTML=data.map(x=>{const portion=x.surah_name?x.surah_name:(x.page_number?`Page ${x.page_number}`:(x.juz_number?`Juz ${x.juz_number}`:'—'));const range=(x.ayah_from||x.ayah_to)?` Ayah ${x.ayah_from||''}-${x.ayah_to||''}`:'';return `<tr><td>${esc(x.lesson_date)}</td><td>${esc(names[x.student_id]||x.student_id)}</td><td>${esc(x.track)}</td><td>${esc(portion+range)}</td><td>${x.completion_percent==null?'—':esc(x.completion_percent)+'%'}</td><td>${esc(x.next_target)}</td></tr>`;}).join('');}
$('progressForm').addEventListener('submit',async e=>{e.preventDefault();if(!canWrite){msg('Quran manage permission নেই।','error');return;}msg('Saving…');const row={student_id:$('studentSelect').value,teacher_id:$('teacherSelect').value||null,lesson_date:$('lessonDate').value,track:$('track').value,surah_name:$('surahName').value.trim()||null,juz_number:$('juzNumber').value?Number($('juzNumber').value):null,ayah_from:$('ayahFrom').value?Number($('ayahFrom').value):null,ayah_to:$('ayahTo').value?Number($('ayahTo').value):null,page_number:$('pageNumber').value?Number($('pageNumber').value):null,sabaq:$('sabaq').value.trim()||null,sabqi:$('sabqi').value.trim()||null,manzil:$('manzil').value.trim()||null,completion_percent:$('completionPercent').value?Number($('completionPercent').value):null,teacher_note:$('teacherNote').value.trim(),next_target:$('nextTarget').value.trim()};const {error}=await supabase.from('qa_quran_progress').insert(row);if(error){msg('Quran progress save করা যায়নি।','error');return;}msg('Progress সফলভাবে save হয়েছে।','success');await loadRecent();});
$('signOut').addEventListener('click',async()=>{await supabase.auth.signOut();location.replace('./');});await init();
