import {createClient} from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
import {getAccess} from './authz.js';
const c=window.QURANER_ALO_CONFIG;const supabase=createClient(c.supabaseUrl,c.supabasePublishableKey,{auth:{autoRefreshToken:true,persistSession:true,detectSessionInUrl:true}});const $=id=>document.getElementById(id);const qs=new URLSearchParams(location.search);const type=qs.get('type');const id=qs.get('id');
const fallback={name_bn:'কোরআনের আলো',name_en:'QURANER ALO',tagline:'কোরআনের আলোয় গড়ি আলোকিত জীবন',address:'',phone:'',email:'',website:'',logo_path:'assets/quraner-alo-logo.jpg'};
function esc(v){return String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));}function money(v){return Number(v||0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});}function date(v){return v?new Date(v).toLocaleString('bn-BD',{dateStyle:'medium',timeStyle:'short'}):'—';}function setParty(rows){$('partyBox').innerHTML=rows.map(([l,v])=>`<div class="field"><span class="label">${esc(l)}:</span><span class="value">${esc(v||'—')}</span></div>`).join('');}function setItems(rows){$('items').innerHTML='<div class="item-row head"><div>বিবরণ (Description)</div><div class="amount">মোট টাকা</div></div>'+rows.map(([l,v])=>`<div class="item-row"><div>${esc(l)}</div><div class="amount">৳ ${money(v)}</div></div>`).join('');}function setTotals(lines){$('totals').innerHTML='<div class="total-box">'+lines.map((x,i)=>`<div class="total-line ${i===lines.length-1?'main':''}"><span>${esc(x[0])}</span><strong>৳ ${money(x[1])}</strong></div>`).join('')+'</div>';}
async function setReceiverName(userId){const el=$('receiverName');if(!el)return;el.textContent='';if(!userId)return;const {data}=await supabase.from('qa_users').select('full_name').eq('user_id',userId).maybeSingle();el.textContent=data?.full_name||'';}
async function schoolProfile(){const {data}=await supabase.from('qa_app_settings').select('value').eq('key','school_profile').maybeSingle();return {...fallback,...(data?.value||{})};}
async function allowed(a){if(!a)return false;if(type==='fee')return a.can('payments.view')||a.can('payments.manage');if(type==='payroll')return a.can('payroll.view')||a.can('payroll.manage');if(type==='voucher')return a.can('vouchers.view')||a.can('vouchers.manage');return false;}
async function renderFee(){const {data:p,error}=await supabase.from('qa_fee_payments').select('payment_id,charge_id,student_id,receipt_no,paid_at,amount,payment_method,reference,received_by,notes').eq('payment_id',id).maybeSingle();if(error||!p)throw new Error('রিসিটটি পাওয়া যায়নি।');const [{data:s},{data:ch},{data:all}]=await Promise.all([supabase.from('qa_students').select('student_code,full_name,phone,email').eq('student_id',p.student_id).maybeSingle(),supabase.from('qa_fee_charges').select('billing_month,expected_amount,discount,previous_due,current_payable').eq('charge_id',p.charge_id).maybeSingle(),supabase.from('qa_fee_payments').select('amount').eq('charge_id',p.charge_id)]);let guardians=[];let guardianPhone='';const {data:links}=await supabase.from('qa_student_guardians').select('guardian_id,is_primary').eq('student_id',p.student_id).order('is_primary',{ascending:false});if(links?.length){const {data:g}=await supabase.from('qa_guardians').select('guardian_id,full_name,relation,phone').in('guardian_id',links.map(x=>x.guardian_id));guardians=g||[];const primaryLink=links.find(x=>x.is_primary)||links[0];guardianPhone=guardians.find(x=>x.guardian_id===primaryLink?.guardian_id)?.phone||guardians.find(x=>x.phone)?.phone||'';}const paid=(all||[]).reduce((x,r)=>x+Number(r.amount||0),0);const due=Math.max(0,Number(ch?.current_payable||0)-paid);$('receiptTitle').textContent='OFFICIAL PAYMENT RECEIPT';$('receiptNo').textContent=`Receipt No: ${p.receipt_no}`;$('receiptDate').textContent=`তারিখ: ${date(p.paid_at)}`;await setReceiverName(p.received_by);setParty([['স্টুডেন্ট আইডি',s?.student_code],['স্টুডেন্টের নাম',s?.full_name],['অভিভাবক',guardians.map(x=>`${x.full_name} (${x.relation})`).join(', ')],['অভিভাবকের ফোন',guardianPhone||s?.phone],['পেমেন্ট মাস',ch?.billing_month],['পেমেন্ট মাধ্যম',p.payment_method],['রেফারেন্স',p.reference]]);setItems([['মাসিক টিউশন/ফি',p.amount]]);setTotals([['সর্বমোট পাওনা',ch?.current_payable||0],['এই পেমেন্ট',p.amount],['অবশিষ্ট বকেয়া',due]]);$('notes').innerHTML=p.notes?`নোট: ${esc(p.notes)}`:'';}
async function renderPayroll(){const {data:p,error}=await supabase.from('qa_payroll_records').select('payroll_id,employee_user_id,employee_type,employee_ref_id,employee_code_snapshot,employee_name_snapshot,created_by,payroll_month,basic,allowance,bonus,overtime,deduction,leave_deduction,advance,adjustment,net_payable,status,paid_at,payment_method,payment_reference,notes').eq('payroll_id',id).maybeSingle();if(error||!p)throw new Error('Salary record পাওয়া যায়নি।');let e={code:p.employee_code_snapshot||'—',name:p.employee_name_snapshot||'—',type:p.employee_type==='teacher'?'Teacher':'Helper',phone:'',email:'',extra:''};if(p.employee_type==='teacher'){const {data:t}=await supabase.from('qa_teachers').select('teacher_code,full_name,full_name_bn,phone,email,specialization').eq('teacher_id',p.employee_ref_id).maybeSingle();if(t)e={code:t.teacher_code,name:t.full_name_bn||t.full_name,type:'Teacher',phone:t.phone,email:t.email,extra:t.specialization||''};}else{const {data:s}=await supabase.from('qa_staff').select('staff_code,full_name,phone,email').eq('staff_id',p.employee_ref_id).maybeSingle();if(s)e={code:s.staff_code,name:s.full_name,type:'Helper',phone:s.phone,email:s.email,extra:''};}if(!e.code||!e.name)throw new Error('Employee profile পাওয়া যায়নি।');$('receiptTitle').textContent='OFFICIAL SALARY RECEIPT';$('receiptNo').textContent=`Payroll ID: ${p.payroll_id.slice(0,8).toUpperCase()}`;$('receiptDate').textContent=`তারিখ: ${date(p.paid_at)}`;await setReceiverName(p.created_by);setParty([['কর্মী আইডি',e.code],['নাম',e.name],['ধরন',e.type],['ফোন',e.phone],['Email',e.email],['মাস',p.payroll_month],['পেমেন্ট মাধ্যম',p.payment_method],['রেফারেন্স',p.payment_reference]]);const payrollItems=[['Basic Salary',p.basic],['Allowance',p.allowance],['Bonus',p.bonus],['Overtime',p.overtime],['Deduction',-Number(p.deduction||0)],['Leave Deduction',-Number(p.leave_deduction||0)],['Advance',-Number(p.advance||0)],['Adjustment',p.adjustment]].filter(([,value])=>Math.abs(Number(value||0))>0);setItems(payrollItems);setTotals([['Net Payable',p.net_payable]]);$('notes').innerHTML=`Status: ${esc(p.status||'draft')}${p.notes?` · ${esc(p.notes)}`:''}`;}
async function renderVoucher(){
  const {data:v,error}=await supabase.from('qa_vouchers').select('voucher_id,voucher_no,voucher_type,voucher_date,amount,account_name,party_name,reference,description,status,created_by,source_type,source_id').eq('voucher_id',id).maybeSingle();
  if(error||!v)throw new Error('Voucher পাওয়া যায়নি।');
  if(v.source_type==='finance_transaction'){
    const {data:t,error:te}=await supabase.from('qa_finance_transactions').select('transaction_date,direction,category,amount,account_name,reference,description').eq('transaction_id',v.source_id).maybeSingle();
    if(te)throw te;
    if(t){
      const income=t.direction==='income';
      $('receiptTitle').textContent=income?'OFFICIAL INCOME RECEIPT':'OFFICIAL EXPENSE RECEIPT';
      $('receiptNo').textContent='Voucher No: '+v.voucher_no;
      $('receiptDate').textContent='তারিখ: '+date(v.voucher_date);
      await setReceiverName(v.created_by);
      setParty([['ধরন',income?'Income':'Expense'],['ক্যাটাগরি',t.category],['হিসাব/মাধ্যম',t.account_name],['রেফারেন্স',t.reference],['স্ট্যাটাস',v.status],['বিবরণ',t.description]]);
      setItems([[t.description||t.category|| (income?'Income':'Expense'),v.amount]]);
      setTotals([[(income?'মোট আয়':'মোট ব্যয়'),v.amount]]);
      $('notes').innerHTML=t.description?'বিবরণ: '+esc(t.description):'';
      return;
    }
  }
  const donation=v.voucher_type==='donation';
  const expense=v.voucher_type==='expense';
  $('receiptTitle').textContent=donation?'DONATION RECEIPT':expense?'OFFICIAL EXPENSE RECEIPT':'OFFICIAL VOUCHER';
  $('receiptNo').textContent='Voucher No: '+v.voucher_no;
  $('receiptDate').textContent='তারিখ: '+date(v.voucher_date);
  await setReceiverName(v.created_by);
  setParty([[donation?'দাতার নাম':'প্রাপক/পার্টির নাম',v.party_name],['ভাউচার ধরন',v.voucher_type],['হিসাব/মাধ্যম',v.account_name],['রেফারেন্স',v.reference],['স্ট্যাটাস',v.status]]);
  setItems([[v.description || (donation?'Donation Received':expense?'Expense':'Voucher Transaction'),v.amount]]);
  setTotals([[donation?'গ্রহণকৃত অনুদান':expense?'মোট খরচ':'মোট পরিমাণ',v.amount]]);
  $('notes').innerHTML=v.description?'বিবরণ: '+esc(v.description):'';
}
async function init(){try{if(!id||!['fee','payroll','voucher'].includes(type))throw new Error('রিসিটের তথ্য সঠিক নয়।');const access=await getAccess(supabase);if(!await allowed(access))throw new Error('এই রিসিট দেখার permission আপনার account-এ নেই।');const profile=await schoolProfile();$('schoolBn').textContent=profile.name_bn||fallback.name_bn;const englishName=profile.name_en||fallback.name_en;$('schoolEn').innerHTML=String(englishName).trim().split(/\s+/).map((word,index)=>index<2&&word?`<span class="school-en-initial">${esc(word.charAt(0))}</span>${esc(word.slice(1))}`:esc(word)).join(' ');$('tagline').textContent=profile.tagline||'';$('contact').textContent=[profile.address,profile.phone,profile.email].filter(Boolean).join('  |  ');$('footerSchool').textContent=profile.name_bn||fallback.name_bn;const logo=profile.logo_path||fallback.logo_path;$('logo').src=logo;$('watermark').src=logo;if(type==='fee')await renderFee();else if(type==='payroll')await renderPayroll();else await renderVoucher();$('receipt').classList.remove('hidden');}catch(e){$('error').textContent=e.message||'রিসিট load করা যায়নি।';$('error').classList.remove('hidden');}}
$('printBtn').addEventListener('click',()=>window.print());$('closeBtn').addEventListener('click',()=>window.close());init();
