import {createClient} from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
import {getAccess} from './authz.js';
const c=window.QURANER_ALO_CONFIG;const supabase=createClient(c.supabaseUrl,c.supabasePublishableKey,{auth:{autoRefreshToken:true,persistSession:true,detectSessionInUrl:true}});const $=id=>document.getElementById(id);
const money=v=>`৳${Number(v||0).toLocaleString('en-BD',{maximumFractionDigits:2})}`;const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
function card(title,body){return `<section class="report-card"><h3>${title}</h3>${body}</section>`}
async function count(table,filter){let q=supabase.from(table).select('*',{count:'exact',head:true});if(filter)q=filter(q);const {count,error}=await q;if(error)throw error;return count||0}
async function loadReports(a){const grid=$('reportGrid');const sections=[];
if(a.can('students.view')||a.can('students.manage')){const [total,active,portal]=await Promise.all([count('qa_students'),count('qa_students',q=>q.eq('status','active')),count('qa_students',q=>q.not('user_id','is',null))]);sections.push(card('Students',`<div class="big">${total}</div><table><tr><td>Active</td><td>${active}</td></tr><tr><td>Portal activated</td><td>${portal}</td></tr><tr><td>Not activated</td><td>${Math.max(0,total-portal)}</td></tr></table>`));}
if(a.can('attendance.view')||a.can('attendance.manage')){const start=new Date();start.setDate(1);const monthStart=start.toISOString().slice(0,10);const [today,month]=await Promise.all([count('qa_attendance',q=>q.eq('attendance_date',new Date().toISOString().slice(0,10))),count('qa_attendance',q=>q.gte('attendance_date',monthStart))]);sections.push(card('Attendance',`<div class="big">${month}</div><table><tr><td>Today</td><td>${today}</td></tr><tr><td>This month</td><td>${month}</td></tr></table>`));}
if(a.can('quran.view')||a.can('quran.manage')){const {data,error}=await supabase.from('qa_quran_progress').select('lesson_date,track,completion_percent,next_target').order('lesson_date',{ascending:false}).limit(10);if(error)throw error;const avg=(data||[]).length?(data.reduce((s,x)=>s+Number(x.completion_percent||0),0)/data.length):0;sections.push(card('Quran Progress',`<div class="big">${Math.round(avg)}%</div><table><tr><td>Recent entries</td><td>${data.length}</td></tr><tr><td>Latest track</td><td>${esc(data[0]?.track||'—')}</td></tr><tr><td>Next target</td><td>${esc(data[0]?.next_target||'—')}</td></tr></table>`));}
if(a.can('fees.view')||a.can('fees.manage')){const {data,error}=await supabase.from('qa_fee_charges').select('current_payable,status').neq('status','paid');if(error)throw error;const due=(data||[]).reduce((s,x)=>s+Number(x.current_payable||0),0);sections.push(card('Fees Due',`<div class="big">${money(due)}</div><table><tr><td>Open charges</td><td>${data.length}</td></tr></table>`));}
if(a.can('finance.view')||a.can('finance.manage')){const {data,error}=await supabase.from('qa_finance_transactions').select('direction,amount').limit(5000);if(error)throw error;const income=(data||[]).filter(x=>x.direction==='income').reduce((s,x)=>s+Number(x.amount||0),0),expense=(data||[]).filter(x=>x.direction==='expense').reduce((s,x)=>s+Number(x.amount||0),0);sections.push(card('Finance',`<div class="big">${money(income-expense)}</div><table><tr><td>Income</td><td>${money(income)}</td></tr><tr><td>Expense</td><td>${money(expense)}</td></tr></table>`));}
if(a.can('payroll.view')||a.can('payroll.manage')){const {data,error}=await supabase.from('qa_payroll_records').select('net_payable,status,payroll_month').order('payroll_month',{ascending:false}).limit(100);if(error)throw error;const total=(data||[]).filter(x=>x.status!=='cancelled').reduce((s,x)=>s+Number(x.net_payable||0),0);sections.push(card('Payroll',`<div class="big">${money(total)}</div><table><tr><td>Recent records</td><td>${data.length}</td></tr><tr><td>Latest month</td><td>${esc(data[0]?.payroll_month||'—')}</td></tr></table>`));}
if(a.can('reports.view')||a.profile.role==='owner'||a.profile.role==='admin'){sections.push(card('Reporting Access','<p class="report-muted">এই account-এর reports permission সক্রিয়। উপরোক্ত available domains live data থেকে তৈরি হয়েছে।</p>'));}
if(!sections.length)sections.push(card('No report data','<p class="report-muted">আপনার account-এর জন্য report-viewable module permission পাওয়া যায়নি।</p>'));grid.innerHTML=sections.join('');}
async function init(){const a=await getAccess(supabase);if(!a){await supabase.auth.signOut();location.replace('./');return;}if(!a.can('reports.view')&&a.profile.role!=='owner'&&a.profile.role!=='admin'){$('loading').textContent='Reports দেখার permission আপনার account-এ নেই।';return;}try{await loadReports(a);$('loading').classList.add('hidden');$('app').classList.remove('hidden');}catch(e){console.error(e);$('message').textContent='Report data load করা যায়নি।';$('message').className='message-inline error';$('loading').classList.add('hidden');$('app').classList.remove('hidden');}}
$('printReport').addEventListener('click',()=>window.print());$('signOut').addEventListener('click',async()=>{await supabase.auth.signOut();location.replace('./');});init();
