import {createClient} from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
import {getAccess} from './authz.js';
const c=window.QURANER_ALO_CONFIG;const supabase=createClient(c.supabaseUrl,c.supabasePublishableKey,{auth:{autoRefreshToken:true,persistSession:true,detectSessionInUrl:true}});const $=id=>document.getElementById(id);
const defaults={name_bn:'কোরআনের আলো',name_en:'QURANER ALO',tagline:'কোরআনের আলোয় গড়ি আলোকিত জীবন',address:'',phone:'',email:'',website:'',logo_path:'assets/quraner-alo-logo.jpg'};
function msg(t,type=''){ $('message').textContent=t;$('message').className=`message-inline ${type}`.trim(); }
function setProfile(v){const x={...defaults,...(v||{})};$('nameBn').value=x.name_bn??'';$('nameEn').value=x.name_en??'';$('tagline').value=x.tagline??'';$('address').value=x.address??'';$('phone').value=x.phone??'';$('email').value=x.email??'';$('website').value=x.website??'';$('logoPath').value=x.logo_path??defaults.logo_path;$('logoPreview')?.setAttribute('src',x.logo_path||defaults.logo_path);}
async function init(){const access=await getAccess(supabase);if(!access){await supabase.auth.signOut();location.replace('./');return;}if(!access.can('settings.manage')){$('loading').textContent='School Profile পরিবর্তনের permission আপনার account-এ নেই।';return;}const {data,error}=await supabase.from('qa_app_settings').select('value').eq('key','school_profile').maybeSingle();if(error){$('loading').textContent='School Profile load করা যায়নি।';return;}setProfile(data?.value);$('loading').classList.add('hidden');$('app').classList.remove('hidden');}
$('profileForm').addEventListener('submit',async e=>{e.preventDefault();const profile={name_bn:$('nameBn').value.trim(),name_en:$('nameEn').value.trim(),tagline:$('tagline').value.trim(),address:$('address').value.trim(),phone:$('phone').value.trim(),email:$('email').value.trim(),website:$('website').value.trim(),logo_path:$('logoPath').value.trim()||defaults.logo_path};if(!profile.name_bn||!profile.address||!profile.phone||!profile.email){msg('বাংলা নাম, ঠিকানা, ফোন ও Email পূরণ করুন।','error');return;}msg('Saving…');const {error}=await supabase.from('qa_app_settings').upsert({key:'school_profile',value:profile,updated_at:new Date().toISOString()},{onConflict:'key'});if(error){msg('School Profile save করা যায়নি।','error');return;}msg('প্রতিষ্ঠানের তথ্য সফলভাবে Save/Update হয়েছে।','success');});
$('logoPath').addEventListener('input',()=>{const p=$('logoPath').value.trim();$('logoPreview')?.setAttribute('src',p||defaults.logo_path)});
$('signOut').addEventListener('click',async()=>{await supabase.auth.signOut();location.replace('./');});init();
