import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const c=window.QURANER_ALO_CONFIG;const supabase=createClient(c.supabaseUrl,c.supabasePublishableKey,{auth:{autoRefreshToken:true,persistSession:true}});const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
async function init(){const {data:{session}}=await supabase.auth.getSession();if(!session){location.replace('./');return;}const {data:p,error:pe}=await supabase.from('qa_students').select('student_id,student_code,full_name,status').eq('user_id',session.user.id).maybeSingle();if(pe||!p||p.status!=='active'){await supabase.auth.signOut();location.replace('./');return;}$('loginId').textContent=p.student_code;$('studentName').textContent=p.full_name;$('studentCode').textContent=p.student_code;$('studentStatus').textContent=p.status;
const [en,att,qr,fc,fp]=await Promise.all([supabase.from('qa_enrollments').select('course_code,start_date,end_date,status,notes').eq('student_id',p.student_id).order('start_date',{ascending:false}),supabase.from('qa_attendance').select('attendance_date,status,remarks').eq('student_id',p.student_id).order('attendance_date',{ascending:false}).limit(12),supabase.from('qa_quran_progress').select('lesson_date,track,surah_name,juz_number,ayah_from,ayah_to,completion_percent,teacher_note,next_target').eq('student_id',p.student_id).order('lesson_date',{ascending:false}).limit(8),supabase.from('qa_fee_charges').select('billing_month,expected_amount,discount,previous_due,current_payable,due_date,status').eq('student_id',p.student_id).order('billing_month',{ascending:false}).limit(6),supabase.from('qa_fee_payments').select('receipt_no,paid_at,amount,payment_method').eq('student_id',p.student_id).order('paid_at',{ascending:false}).limit(10)]);
$('enrollments').innerHTML=(en.data||[]).map(x=>`<li><b>${esc(x.course_code)}</b> · ${esc(x.status)}<br><span class="muted">Start: ${esc(x.start_date||'—')}</span></li>`).join('')||'<li>No enrollment found.</li>';
$('quran').innerHTML=(qr.data||[]).map(x=>`<li><b>${esc(x.track)}</b> · ${esc(x.surah_name||((x.juz_number&&'Juz '+x.juz_number)||'Lesson'))}<br>${x.completion_percent==null?'':esc(x.completion_percent)+'%'} ${esc(x.next_target||'')}</li>`).join('')||'<li>No Quran progress yet.</li>';
$('fees').innerHTML=(fc.data||[]).map(x=>`<li><b>${esc(x.billing_month)}</b><br>Payable: ${esc(x.current_payable)} · ${esc(x.status)}</li>`).join('')||'<li>No fee record yet.</li>';
$('attendanceRows').innerHTML=(att.data||[]).map(x=>`<tr><td>${esc(x.attendance_date)}</td><td>${esc(x.status)}</td><td>${esc(x.remarks||'')}</td></tr>`).join('')||'<tr><td colspan="3">No attendance record.</td></tr>';
$('paymentRows').innerHTML=(fp.data||[]).map(x=>`<tr><td>${esc(x.receipt_no)}</td><td>${esc(x.paid_at?new Date(x.paid_at).toLocaleDateString():'' )}</td><td>${esc(x.amount)}</td><td>${esc(x.payment_method)}</td></tr>`).join('')||'<tr><td colspan="4">No payment record.</td></tr>';
$('loading').classList.add('hidden');$('app').classList.remove('hidden');}
$('signOut').addEventListener('click',async()=>{await supabase.auth.signOut();location.replace('./');});init().catch(e=>{console.error(e);$('loading').textContent='Portal load করা যায়নি।';});