import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const config = window.QURANER_ALO_CONFIG;
const supabase = createClient(config.supabaseUrl, config.supabasePublishableKey, { auth: { autoRefreshToken: true, persistSession: true, detectSessionInUrl: true } });
const $ = (id) => document.getElementById(id);
let allStudents = [];
function escapeHtml(value) { return String(value ?? '').replace(/[&<>\"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c])); }
function redirectToLogin(){ window.location.replace('./'); }
function setMessage(text, type=''){ $('message').textContent = text; $('message').style.color = type === 'error' ? '#b33b3b' : ''; }
function activationBadge(userId){ return userId ? '<span class="active-badge on">Activated</span>' : '<span class="active-badge off">Not activated</span>'; }
function renderStudents(list){ $('countLabel').textContent = `${list.length} জন`; $('studentRows').innerHTML = list.map(s => `<tr><td class="student-code">${escapeHtml(s.student_code)}</td><td>${escapeHtml(s.full_name)}</td><td>${escapeHtml(s.phone)}</td><td>${escapeHtml(s.admission_date || '')}</td><td><span class="active-badge ${s.status==='active'?'on':'off'}">${escapeHtml(s.status)}</span></td><td>${activationBadge(s.user_id)}</td></tr>`).join('') || '<tr><td colspan="6">কোনো শিক্ষার্থী পাওয়া যায়নি।</td></tr>'; }
async function loadStudents(){ const {data,error}=await supabase.from('qa_students').select('student_id,student_code,full_name,phone,admission_date,status,user_id,email').order('created_at',{ascending:false}); if(error) throw error; allStudents=data||[]; renderStudents(allStudents); }
async function canManage(profile){ return profile.role==='owner' || profile.role==='admin'; }
async function init(){ const {data:{session}}=await supabase.auth.getSession(); if(!session) return redirectToLogin(); const {data:profile,error}=await supabase.from('qa_users').select('user_id,role,active').eq('user_id',session.user.id).maybeSingle(); if(error || !profile || !profile.active){ await supabase.auth.signOut(); return redirectToLogin(); } $('loading').classList.add('hidden'); $('app').classList.remove('hidden'); if(await canManage(profile)) $('newStudent').classList.remove('hidden'); else $('newStudent').classList.add('hidden'); try{ await loadStudents(); }catch(e){ console.error(e); setMessage('Student list load করা যায়নি।','error'); } }
$('newStudent').addEventListener('click',()=> $('studentFormPanel').classList.toggle('hidden'));
$('cancelStudent').addEventListener('click',()=>{ $('studentForm').reset(); $('studentFormPanel').classList.add('hidden'); });
$('search').addEventListener('input',()=>{ const q=$('search').value.trim().toLowerCase(); if(!q) return renderStudents(allStudents); renderStudents(allStudents.filter(s => [s.student_code,s.full_name,s.phone,s.email].join(' ').toLowerCase().includes(q))); });
$('studentForm').addEventListener('submit', async (event)=>{ event.preventDefault(); const form=new FormData(event.currentTarget); const payload={ full_name:String(form.get('full_name')||'').trim(), full_name_bn:String(form.get('full_name_bn')||'').trim()||null, gender:String(form.get('gender')||'unspecified'), date_of_birth:form.get('date_of_birth')||null, phone:String(form.get('phone')||'').trim(), email:String(form.get('email')||'').trim(), admission_date:form.get('admission_date')||new Date().toISOString().slice(0,10), status:String(form.get('status')||'active'), notes:String(form.get('notes')||'').trim() }; const {data,error}=await supabase.from('qa_students').insert(payload).select('student_id,student_code,full_name,phone,admission_date,status,user_id').single(); if(error){ console.error(error); setMessage('Student save করা যায়নি।','error'); return; } await supabase.from('qa_audit_log').insert({actor_user_id:(await supabase.auth.getUser()).data.user?.id,action:'student.created',entity_type:'qa_students',entity_id:data.student_id,metadata:{student_code:data.student_code}}); event.currentTarget.reset(); $('studentFormPanel').classList.add('hidden'); setMessage(`শিক্ষার্থী ${data.student_code} সফলভাবে যুক্ত হয়েছে। Portal activation: Not activated.`); await loadStudents(); });
$('signOut').addEventListener('click', async()=>{ await supabase.auth.signOut(); redirectToLogin(); });
init().catch(e=>{ console.error(e); $('loading').textContent='Page load করা যায়নি।'; });
