import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const c=window.QURANER_ALO_CONFIG;const supabase=createClient(c.supabaseUrl,c.supabasePublishableKey,{auth:{autoRefreshToken:true,persistSession:true}});const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
function statusClass(value){const v=String(value||'').toLowerCase();if(['active','present','paid'].includes(v))return 'on';if(['absent','inactive','overdue'].includes(v))return 'off';return '';}
async function init(){const {data:{session}}=await supabase.auth.getSession();if(!session){location.replace('./');return;}const {data:p,error:pe}=await supabase.from('qa_students').select('student_id,student_code,full_name,status,phone,email').eq('user_id',session.user.id).maybeSingle();if(pe||!p||p.status!=='active'){await supabase.auth.signOut();location.replace('./');return;}$('loginId').textContent=p.student_code;$('studentName').textContent=p.full_name;$('studentCode').textContent=p.student_code;$('studentStatus').textContent=p.status;
const [en,link,att,qr,fc,fp]=await Promise.all([supabase.from('qa_enrollments').select('course_code,start_date,end_date,status,teacher_user_id,notes').eq('student_id',p.student_id).order('start_date',{ascending:false}),supabase.from('qa_student_guardians').select('guardian_id,is_primary').eq('student_id',p.student_id),supabase.from('qa_attendance').select('attendance_date,status,remarks').eq('student_id',p.student_id).order('attendance_date',{ascending:false}).limit(12),supabase.from('qa_quran_progress').select('lesson_date,track,surah_name,juz_number,ayah_from,ayah_to,completion_percent,teacher_note,next_target').eq('student_id',p.student_id).order('lesson_date',{ascending:false}).limit(8),supabase.from('qa_fee_charges').select('billing_month,expected_amount,discount,previous_due,current_payable,due_date,status').eq('student_id',p.student_id).order('billing_month',{ascending:false}).limit(6),supabase.from('qa_fee_payments').select('receipt_no,paid_at,amount,payment_method').eq('student_id',p.student_id).order('paid_at',{ascending:false}).limit(10)]);
const enrollments=en.data||[];const guardianLinks=link.data||[];
let guardianMap={};if(guardianLinks.length){const ids=guardianLinks.map(x=>x.guardian_id);const {data:gs}=await supabase.from('qa_guardians').select('guardian_id,full_name,relation,phone,email,address').in('guardian_id',ids);guardianMap=Object.fromEntries((gs||[]).map(x=>[x.guardian_id,x]));}
let teacherMap={};const teacherUserIds=[...new Set(enrollments.map(x=>x.teacher_user_id).filter(Boolean))];if(teacherUserIds.length){const {data:ts}=await supabase.from('qa_teachers').select('user_id,teacher_code,full_name,full_name_bn,phone,specialization').in('user_id',teacherUserIds);teacherMap=Object.fromEntries((ts||[]).map(x=>[x.user_id,x]));}
$('guardians').innerHTML=guardianLinks.map(g=>{const x=guardianMap[g.guardian_id];if(!x)return '';return `<div class="portal-stat"><small>${esc(x.relation||'Guardian')}${g.is_primary?' · Primary':''}</small><strong>${esc(x.full_name)}</strong><span class="muted">${esc(x.phone||'')}</span>${x.email?`<span class="muted">${esc(x.email)}</span>`:''}${x.address?`<span class="muted">${esc(x.address)}</span>`:''}</div>`;}).join('')||'<p class="portal-note">Guardian information has not been added yet.</p>';
$('enrollments').innerHTML=enrollments.map(x=>{const t=teacherMap[x.teacher_user_id];return `<div class="portal-stat"><small>${esc(x.course_code)} · <span class="active-badge ${statusClass(x.status)}">${esc(x.status)}</span></small><strong>${esc(t?.full_name||'Teacher not assigned')}</strong>${t?.specialization?`<span class="muted">${esc(t.specialization)}</span>`:''}<span class="muted">Start: ${esc(x.start_date||'—')} · End: ${esc(x.end_date||'—')}</span>${x.notes?`<span class="muted">${esc(x.notes)}</span>`:''}</div>`;}).join('')||'<p class="portal-note">No enrollment found.</p>';
$('quran').innerHTML=(qr.data||[]).map(x=>`<li><b>${esc(x.track)}</b> · ${esc(x.surah_name||((x.juz_number&&'Juz '+x.juz_number)||'Lesson'))}<br>${x.completion_percent==null?'':esc(x.completion_percent)+'%'} ${esc(x.next_target||'')}</li>`).join('')||'<li>No Quran progress yet.</li>';
$('fees').innerHTML=(fc.data||[]).map(x=>`<li><b>${esc(x.billing_month)}</b><br>Payable: ${esc(x.current_payable)} · <span class="active-badge ${statusClass(x.status)}">${esc(x.status)}</span></li>`).join('')||'<li>No fee record yet.</li>';
const attendance=att.data||[];$('presentCount').textContent=attendance.filter(x=>x.status==='present').length;$('absentCount').textContent=attendance.filter(x=>x.status==='absent').length;$('otherAttendanceCount').textContent=attendance.filter(x=>!['present','absent'].includes(x.status)).length;$('attendanceRows').innerHTML=attendance.map(x=>`<tr><td>${esc(x.attendance_date)}</td><td><span class="active-badge ${statusClass(x.status)}">${esc(x.status)}</span></td><td>${esc(x.remarks||'')}</td></tr>`).join('')||'<tr><td colspan="3">No attendance record.</td></tr>';
$('paymentRows').innerHTML=(fp.data||[]).map(x=>`<tr><td>${esc(x.receipt_no)}</td><td>${esc(x.paid_at?new Date(x.paid_at).toLocaleDateString():'' )}</td><td>${esc(x.amount)}</td><td>${esc(x.payment_method)}</td></tr>`).join('')||'<tr><td colspan="4">No payment record.</td></tr>';
const notes=[];enrollments.filter(x=>x.notes).slice(0,3).forEach(x=>notes.push(`${x.course_code}: ${x.notes}`));(qr.data||[]).slice(0,3).forEach(x=>{if(x.teacher_note)notes.push(`Quran: ${x.teacher_note}`);if(x.next_target)notes.push(`Next target: ${x.next_target}`);});$('notes').innerHTML=notes.length?notes.map(x=>`<div>${esc(x)}</div>`).join(''):'No new notes.';
$('loading').classList.add('hidden');$('app').classList.remove('hidden');}
$('signOut').addEventListener('click',async()=>{await supabase.auth.signOut();location.replace('./');});init().catch(e=>{console.error(e);$('loading').textContent='Portal load করা যায়নি।';});